server:
  port:  80
  servlet:
    encoding:
      charset:  utf-8
      force:  true

      
spring:
  mvc:
    view:
      prefix:  /WEB-INF/view/
      suffix:  .jsp
  servlet: # fileupload
    multipart:
      max-file-size:  20MB
      max-request-size:  20MB  
        
  datasource:
    url: jdbc:mysql://localhost:3306/testbank?serverTimeZone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: asd1234
          
  # h2:
  #  console:
  #    enabled: true
  # output:
  #  ansi:
  #    enabled: always    
      
mybatis: 
 mapper-locations:
  - classpath:mapper/**.xml
 configuration:
   map-underscore-to-camel-case: true 
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
   
logging:
  level:
    org.mybatis: DEBUG # MyBatis 로깅 레벨을 DEBUG로 설정하여, 실행되는 SQL 쿼리와 내부 로깅 정보를 콘솔에 출력합니다.

# 1. 코드 추가 
file:
  upload-dir: uploads/  # yml 파일에 파일 업로드 디렉토리 경로 설정
        
      